### ISSUE TITLE
agg_query_dq_detailed_result [NOT_IMPLEMENTED] toJSON() is not implemented using version 2.2.1

### ISSUE THREAD

**Issue by maheshyadav921** [Nike-Inc/spark-expectations#120]
**Summary**
I am implementing Spark Expectations using version 2.2.1 and DBR 15 ( Spark 3.5 ) in a shared cluster. I am facing an issue in implementing with query dq check and sharing my error log below.

**To Reproduce**
Running `agg_query_dq_detailed_result` on Spark Connect will cause the following error:
```
SparkExpectationsMiscException: error occurred while processing spark expectations error occurred while executing func_process error occurred while running expectations error occurred while running agg_query_dq_detailed_result [NOT_IMPLEMENTED] toJSON() is not implemented.
File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.11/site-packages/spark_expectations/utils/actions.py:346, in SparkExpectationsActions.agg_query_dq_detailed_result(_context, _dq_rule, df, querydq_output, _source_dq_status, _target_dq_status)
    330     for _key, _querydq_query in sub_key_value.items():
    331         querydq_output.append(
    332             (
    333                 _context.get_run_id,
    334                 _dq_rule["product_id"],
    335                 _dq_rule["table_name"],
    336                 _dq_rule["rule"],
    337                 _key,
    338                 _query_prefix,
    339                 dict(
    340                     [
    341                         (
    342                             _key,
    343                             _context.spark.sql(
    344                                 _dq_rule["expectation" + "_" + _key]
    345                             )
--> 346                             .toJSON()
    347                             .collect(),
    348                         )
    349                     ]
    350                 ),
    351                 _context.get_run_date,
    352             )
    353         )
    355 if SparkExpectationsActions.match_parentheses(_dq_rule["expectation"]):
File /databricks/spark/python/pyspark/sql/connect/dataframe.py:2425, in DataFrame.toJSON(self, use_unicode)
   2424 def toJSON(self, use_unicode: bool = True) -> "RDD[str]":
-> 2425     raise PySparkNotImplementedError(
   2426         error_class="NOT_IMPLEMENTED",
   2427         message_parameters={"feature": "toJSON()"},
   2428     )
PySparkNotImplementedError: [NOT_IMPLEMENTED] toJSON() is not implemented.
```

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

[spark-expectation-log-DBR15.txt](https://github.com/user-attachments/files/18114793/spark-expectation-log-DBR15.txt)
![Screenshot 2024-12-11 at 2 53 28 PM](https://github.com/user-attachments/assets/e8934f0f-2b4d-40c1-84e2-e8ab1eccbe59)

**Comment by dannymeijer** [comment]
Thanks for highlighting this. Rootcause of this is related to the implementation of this line:
https://github.com/Nike-Inc/spark-expectations/blob/9500ed9ab4328ddf37c49cdb3063c71d6a37584e/spark_expectations/utils/actions.py#L346

And the problem particularly exists when using Spark connect.
Error is raised by connect code: [see here for reference](https://github.com/Nike-Inc/spark-expectations/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=%5BBUG%5D+Please+add+your+bug+title+here).

Solution would be for us to remove the need for `toJSON`. We're going to have to add a test for this specifically.
