### ISSUE TITLE
[FEATURE] Reader and Writer as plugins to support tables stored in different systems Bigquery, Snowflake etc

### ISSUE THREAD

**Issue by phanikumarvemuri** [Nike-Inc/spark-expectations#14]
**Is your feature request related to a problem? Please describe.**
Instead of hard coding the table locations to `delta` we can refactor the reader and writer to support various systems so that the `spark-expectations` can be run on tables stored in different warehouses. 

**Describe the solution you'd like**
Right now the spark session assumes the tables are stored local/hive catalog for both read and write. Instead they can be configurable and reader, writer can be chosen based on the `storage_type`  or `warehouse_type` which can be a user argument.  

https://github.com/Nike-Inc/spark-expectations/blob/78c47598082c96332e5755427a6c767ae22faa0d/spark_expectations/utils/reader.py#L149

https://github.com/Nike-Inc/spark-expectations/blob/78c47598082c96332e5755427a6c767ae22faa0d/spark_expectations/sinks/utils/writer.py#L71

Below are the current arguments passed.

```
@se.with_expectations(
    se.reader.get_rules_from_table(
        product_rules_table="dq_spark_local.dq_rules",
        target_table_name="dq_spark_local.customer_order",
        dq_stats_table_name="dq_spark_local.dq_stats",
    ),
    write_to_table=True,
    row_dq=True,
    agg_dq={
        user_config.se_agg_dq: True,
        user_config.se_source_agg_dq: True,
        user_config.se_final_agg_dq: True,
    },
    query_dq={
        user_config.se_query_dq: True,
        user_config.se_source_query_dq: True,
        user_config.se_final_query_dq: True,
        user_config.se_target_table_view: "order",
    },
    spark_conf=global_spark_Conf,
)
```
Similar to [yaml](https://docs.getdbt.com/docs/core/connect-data-platform/connection-profiles) we can define  a file with all the properties defined for the respective warehouse including how to authenticate, extra args etc.. 

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by asingamaneni** [comment]
@swu121 @phanikumarvemuri Please start the discussion on this and collaborate. Expectation is to see the design document for this change before we proceed further. Thanks for the help, Happy Coding!

**Comment by swu121** [comment]
sounds good - @phanikumarvemuri, what's your preferred form of contact?

**Comment by phanikumarvemuri** [comment]
@swu121, you can reach me at `phaniv99@gmail.com`.  Please let me know if you would like to discuss this on google meet some time this week ?

**Comment by swu121** [comment]
Yea sure

**Comment by asingamaneni** [comment]
> @swu121, you can reach me at `phaniv99@gmail.com`. Please let me know if you would like to discuss this on google meet some time this week ?

Thanks @phanikumarvemuri @swu121 , I have schedule a call for Friday and looking forward to discuss this and finalize the design

**Comment by newfront** [comment]
This is a smart idea for expansion.

**Comment by newfront** [comment]
bonus points for bringing [Trino](https://trino.io) and [SQLAlchemy](https://docs.sqlalchemy.org/en/20/intro.html) for handling the traditional and even non-traditional db connections. 

I love the idea of making the expectations work with "any" common backend.

**Comment by asingamaneni** [comment]
Tagging the discussion on this topic - #25
