### ISSUE TITLE
[FEATURE] We should not require delta

### ISSUE THREAD

**Issue by holdenk** [Nike-Inc/spark-expectations#35]
**Is your feature request related to a problem? Please describe.**
I use iceberg for the most part but various parts including writing stats seem to be hard coded to delta.

**Describe the solution you'd like**

Use Spark's table writing mechanisms.

**Describe alternatives you've considered**

Installing delta, but I don't want to.

**Additional context**

Trying to override the format to iceberg in options/spark_options/etc. does not work since the format of delta is taking precedence from the way the options are combined.

**Comment by newfront** [comment]
+1. setting `--conf x=y` for the iceberg catalog and other overrides + having the right `spark.jars` in place makes a ton of sense.
