### ISSUE TITLE
[FEATURE] Manage rules in a a central location

### ISSUE THREAD

**Issue by pinnapuvijay** [Nike-Inc/spark-expectations#47]
**Is your feature request related to a problem? Please describe.**
Ability to manage rules using a declarative language like YAML in a central location 

**Describe the solution you'd like**
Manage the rules in a YAML within a git repo. Using git repo for managing rules in YAML format, provides audit and traceability of the changes and also helps follow PR process to move through the environments.

**Describe alternatives you've considered**

**Additional context**

**Comment by asingamaneni** [comment]
This has to be an internal feature, please move to internal request.
