### ISSUE TITLE
[FEATURE] Deploy rules to delta table using CI/CD

### ISSUE THREAD

**Issue by pinnapuvijay** [Nike-Inc/spark-expectations#48]
**Is your feature request related to a problem? Please describe.**
Ability to deploy the rules to delta table through the environments using CI/CD process

**Describe the solution you'd like**
Deploy rules to delta table **dq_rules** using CI/CD(jenkins, etc) pipeline

**Describe alternatives you've considered**

**Additional context**
Additional ability to wipe out existing rules from the table and load all the rules(history load kind) will also be helpful.

**Comment by asingamaneni** [comment]
This has to be an internal feature, please move to internal request.
