### ISSUE TITLE
[FEATURE] Ability to enable/disable rules and create the PR automatically using a standard process/interface

### ISSUE THREAD

**Issue by pinnapuvijay** [Nike-Inc/spark-expectations#49]
**Is your feature request related to a problem? Please describe.**
Ability for production support team(or anybody) to disable/enable rules using a standard process/interface as opposed to running DML manually

**Describe the solution you'd like**
A notebook that would take the inputs to identify the rule that need to be enabled/disabled. The notebook should also create the PR to help keep the rules in the table in sync wth the rules maintained in the git repo.

**Describe alternatives you've considered**

**Additional context**

**Comment by asingamaneni** [comment]
This has to be an internal feature, please move to internal request.
