### ISSUE TITLE
[Features] The following improvements can be applied to the framework 

### ISSUE THREAD

**Issue by phanikumarvemuri** [Nike-Inc/spark-expectations#6]
1. I see the `dq_results` are being set twice to the `_context`. Is it not redundant ?
https://github.com/Nike-Inc/spark-expectations/blob/9f9d3c327a5af487cac8743439efe37d20c33862/spark_expectations/core/expectations.py#L398
https://github.com/Nike-Inc/spark-expectations/blob/9f9d3c327a5af487cac8743439efe37d20c33862/spark_expectations/utils/regulate_flow.py#L151

2. The python udfs `remove_empty_maps` and `get_actions_list` can be replaced with native functions `filter` and `transform` to avoid coverting the objects from java to python and vice versa

3. More information can be provided when raising exception on which rules are causing the process to fail etc when exiting as the information is available to the column. The stats should be pushed down streams before exiting. 
https://github.com/Nike-Inc/spark-expectations/blob/9f9d3c327a5af487cac8743439efe37d20c33862/spark_expectations/utils/actions.py#L288

5. persisting `error_df` dataframe helps at the below step since it is used thrice in the same context
https://github.com/Nike-Inc/spark-expectations/blob/9f9d3c327a5af487cac8743439efe37d20c33862/spark_expectations/sinks/utils/writer.py#L417

**Comment by asingamaneni** [comment]
@phanikumarvemuri The points you mentioned above are valid improvements. Could you please work on these and raise pr along with test results?

**Comment by phanikumarvemuri** [comment]
sure
