### ISSUE TITLE
[BUG] meta_dq_run_date should be called meta_dq_run_datetime in error table

### ISSUE THREAD

**Issue by IMC07** [Nike-Inc/spark-expectations#65]
**Describe the bug**
In the stats table we have the columns meta_dq_run_date (eg. 2024-01-03) and meta_dq_run_datetime (eg. 2024-01-03T09:04:48Z). In the error table we do not have a column called meta_dq_run_datetime, but only meta_dq_run_date, and the format of that one is 2024-01-03T09:04:48Z. So it is actually a datetime, which is confusing.

**Expected behavior**
Rename the column meta_dq_run_date to meta_dq_run_datetime in the error table.

**Comment by asingamaneni** [comment]
@IMC07  This is a good catch, thanks for bringing this up! Would you like to contribute to this?
